name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.5', '8.4', '8.3']
        laravel: ['^13', '^12']
        dependency-version: [prefer-stable, prefer-lowest]
        include:
          - laravel: '^13'
            testbench: '^11'
          - laravel: '^12'
            testbench: '^10'

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Run Pint
        run: vendor/bin/pint --test

      - name: Execute tests
        run: vendor/bin/pest

  coverage:
    runs-on: ubuntu-latest
    name: Coverage

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: curl, mbstring, zip, pcntl
          coverage: pcov

      - name: Install dependencies
        run: |
          composer require "laravel/framework:^13" "orchestra/testbench:^11" --no-interaction --no-update
          composer update --prefer-stable --prefer-dist --no-interaction

      - name: Execute tests with coverage
        run: vendor/bin/pest --coverage-clover coverage.xml --log-junit junit.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: junit.xml
